-- Safe baseline data. No demo users or passwords are created.
INSERT INTO "Organization" ("id","name","orgNumber","email","updatedAt")
VALUES ('11111111-1111-4111-8111-111111111111','Östgöta El Teknik',NULL,'info@ostgotaelteknik.se',now())
ON CONFLICT ("id") DO UPDATE SET "name"=EXCLUDED."name", "updatedAt"=now();

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('86f9f9c3-b94e-4e5b-8abf-1e6f723295e0',NULL,'Superadmin','superadmin',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'bc1574ab-a4bd-4c1d-b2e3-a827e3713e8e',"id",'*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='superadmin' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('1848529c-470c-40a0-8336-d3f3413f5394',NULL,'Bolagsadmin','org-admin',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '4aa913d7-b27b-4a21-8483-ef1ebb5826d3',"id",'persons:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '29f957e4-67e7-4d4f-bd85-4fc53250a8be',"id",'users:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '516a238a-738f-4adc-b913-94224624efd3',"id",'roles:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '9e57b466-c658-465d-abd7-853be3286737',"id",'properties:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '2ae371d2-7e38-4ce1-8b6a-85cd70c19043',"id",'buildings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '0a0c94d5-822b-49c6-ac56-7639de6c5505',"id",'units:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '168d5d34-d6b6-4478-b167-961339d9ba48',"id",'listings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e3a9a39f-c652-416c-83f7-cb811ad28f19',"id",'applications:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '82c6f84a-d0c6-4665-b0db-f5aab76e0eb3',"id",'viewings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '74fff125-7fde-45f7-9390-d3031a1f4558',"id",'offers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '3006837d-8ad6-462a-9c26-eca333cda56a',"id",'contracts:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'ba5a4e90-d1d1-4c8f-8752-7c4314ce242c',"id",'terminations:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '607f2c2f-bf7e-4abe-829d-e1b3dd41c1bd',"id",'inspections:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e30867ac-328b-47a4-a02f-0ed35afd6b31',"id",'invoices:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'ca13576d-6c1e-4afb-884f-17e8f81186cd',"id",'payments:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'd8a1ae78-f94d-4647-98da-0fb2177422a3',"id",'maintenance:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '37cb35fc-29a0-4bdb-93d6-cfa46624bac1',"id",'workorders:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '2eda9015-8dac-4d61-be44-b0cfd1dbda13',"id",'suppliers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '2c5b7b99-7abb-47eb-bbf8-dd29300bf35c',"id",'documents:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8edef1a6-b644-4f00-890b-7a1f9c887442',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a68e2de4-32ae-4eec-982a-341d91f05033',"id",'notifications:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c56a0d82-f08d-4dce-8c7d-77b4f0d6d9d8',"id",'integrations:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8905a14e-69ef-4223-96d0-6f30af329400',"id",'webhooks:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e941c335-010e-41e2-804e-de54ce8a2055',"id",'apikeys:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c7f21dd1-aeec-4f38-85cf-d840be151a8d',"id",'imports:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '49d99b45-c126-4598-8ce5-82463b2815d8',"id",'reports:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '69283f73-9c81-42b8-a7dd-22a8d600e53d',"id",'audit:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'd91bc39e-0000-4fd4-86e5-72edcf36bc76',"id",'settings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='org-admin' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('3dbda51b-93a2-492e-8170-9c8bb4abd92f',NULL,'Fastighetsägare','property-owner',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '12641a72-2670-4d82-8452-01270a20bf3c',"id",'properties:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '7359874d-2e60-4a10-8974-843179cffb54',"id",'buildings:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a8ceee57-f4f9-458f-9237-f14cc9cd94a4',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '19baac62-2b26-4060-bbc9-d5fec85c036a',"id",'listings:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '6f5f5733-f117-4a63-ac10-57404dfa5cf3',"id",'contracts:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'b50a5400-7296-4ded-bbbe-890b4fa5bc83',"id",'invoices:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '1bf6c259-b079-44c5-a81d-546f6b39376b',"id",'payments:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '0e5a4e18-7f86-410c-af9d-1f7815385545',"id",'reports:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'cc713432-7ece-4576-9bdc-fd97b06ba38b',"id",'maintenance:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '9674dd35-17de-4d5d-a059-f5841802190f',"id",'workorders:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '7a08d63b-1340-40a7-9a51-bd9bd5ef48a7',"id",'audit:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-owner' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('d54fc146-d3a2-41be-8e73-e894dc879f5b',NULL,'Förvaltare','property-manager',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '15bbaa8f-0012-4d4f-980d-8a7b7169de5e',"id",'persons:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '7f998223-a7fd-47f1-83ea-24cb551969a1',"id",'properties:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '924d2749-01c8-4d48-b118-4404aa97cc6f',"id",'buildings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '3a114d49-7dbc-4681-9423-188d3fce0d1d',"id",'units:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '83ae146a-e870-444d-aaa0-459379b7e750',"id",'listings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '95487cff-e170-4c89-a8aa-7e59cf4edf0a',"id",'applications:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'fb017720-e6be-40d6-94a0-68da1662c435',"id",'viewings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '9ad0ecd5-5a71-4630-9aa7-a85cbb933976',"id",'offers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '69f8466d-3d83-4293-9e93-7d8f9f907098',"id",'contracts:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'd882676c-d796-42c9-b9dc-16a466fb5c49',"id",'terminations:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '080351bd-f9e8-4deb-a93b-895fb8d4c1bb',"id",'inspections:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '22c62363-e755-4010-b620-5f66028f2cf4',"id",'maintenance:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c1f565f7-ab72-47e5-8657-926fc913c949',"id",'workorders:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'fa0e1ee6-abc1-4b7e-ba49-e37532beb868',"id",'suppliers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '854a3bfb-b574-4adc-8e97-e4a2ba47ee95',"id",'documents:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c3cbf0ac-8e23-4740-ae45-113f57764720',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8b375aa7-95f7-4dcf-814d-4d8625e45d12',"id",'invoices:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '1c5c71b2-a9d2-406b-8407-ed8aa3fc589c',"id",'payments:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c6d1e0a8-3935-44d0-b5f2-af2a0b789513',"id",'imports:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'efe8dbe7-73d5-4fcf-8dce-95d66a5d6c08',"id",'reports:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='property-manager' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('9c34da84-aaeb-4da0-8c6e-209898707f3a',NULL,'Fastighetsvärd','caretaker',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e671985f-dc2e-48c1-a175-c38f1758319e',"id",'properties:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8afbf684-3d1c-495c-b55a-05f3a98ecc76',"id",'buildings:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '96a69b66-dbf9-4544-96d2-b1ba876669de',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '23cc6f03-8d74-4334-95f2-9760911742e5',"id",'maintenance:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '305cc1f8-5b68-4b8d-b30f-067731c9c957',"id",'workorders:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8a29a8d7-b959-4afe-9082-48cb5410764c',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a8e914d2-59d7-4ffa-b759-c1c2ed3266bc',"id",'persons:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '84648f6f-6d3a-4c65-8b5a-cb7644e2dfc4',"id",'documents:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='caretaker' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('031f735e-5a6b-4488-8d25-8930e447374d',NULL,'Uthyrare','leasing-agent',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'd5c455e8-5fef-49d5-aaf3-b86e469a6207',"id",'persons:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a5da0a5f-12bb-4af8-b248-e1249b76a4b4',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a21e7cdc-2fce-408e-88a4-a6724c297529',"id",'units:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'aefb219a-e5dc-44ed-abf1-74a7c3fc84f0',"id",'listings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '593173d1-9342-4f44-82e0-d6f025484e51',"id",'applications:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'f68c2751-fd1e-49d4-973b-b389d8806d24',"id",'viewings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '219c216b-fcb7-4709-ac70-5afe4576494e',"id",'offers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '399b0bf3-9342-413e-bbed-9c6a04ca4d71',"id",'contracts:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '06d4f623-2e61-4899-bb84-24f0930a88f9',"id",'documents:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'dfc2d902-dff5-4e7e-ad81-b4e05ad144e4',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '669cb899-b3b8-4635-8ca2-c746984f9051',"id",'reports:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='leasing-agent' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('98ec33ed-ffae-45c0-85e2-35dd86b14144',NULL,'Försäljningsansvarig','sales-manager',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '9b340a38-fdb5-4711-83f3-7876b8849209',"id",'persons:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'b82b94f4-7f97-4301-bb6f-006af67e4222',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a4df23c4-ce07-4ce1-9798-4ac0daab706a',"id",'units:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'de11c79d-a59a-42ef-a820-95efee22608f',"id",'listings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '1d0597e5-c88c-479c-8cfb-5a4e30b8b398',"id",'viewings:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '88b13c67-4195-41a1-80d5-971ee9df4fb9',"id",'offers:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'fd704b55-f137-4a57-bf49-6c9d65bd3def',"id",'contracts:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '149d62ea-393f-42ad-9d61-8642a7696e76',"id",'documents:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '61dd5a14-7c3f-4857-824a-48edd03c47a0',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '95a627f1-962e-4cce-a4e8-925518b899a1',"id",'reports:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='sales-manager' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('7d0b3a19-9aa0-4473-863a-ce2eb494ae30',NULL,'Ekonom','finance',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '04834fb1-8066-4819-b438-2303bb892351',"id",'persons:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '7bdb2461-4fdd-455e-9c4b-c6dc04a30003',"id",'contracts:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '0d4a00a0-6eab-47c2-a906-ee8bacafd707',"id",'invoices:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '53abb95c-db54-469e-8d81-4abee2ba1357',"id",'payments:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a26b5d77-eb8c-426e-b9ef-7d5850da565e',"id",'integrations:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a2ee1af1-62b1-400e-867e-93eb510f7429',"id",'reports:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '67605309-005b-4819-8f88-1b3eaa025f41',"id",'audit:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='finance' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('87a04046-937b-4a9a-8d04-d3e951c4234d',NULL,'Kundtjänst','customer-service',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '82f426dc-279f-4597-948a-ce08be51b034',"id",'persons:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e164385d-33f2-47ba-b6a5-6be62f6a1028',"id",'persons:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e83691fd-29c7-4935-b2ea-4a0e9ace0787',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '7fc523b7-528f-4128-9599-643975a7e3d6',"id",'listings:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a36ad701-debb-422e-868a-fd5cd8282114',"id",'applications:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '8f2626f7-4435-4924-bf3a-5d0eeeb96c3d',"id",'applications:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a0b73244-1662-4359-ac6c-23fbbdd6ffc1',"id",'contracts:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '9b9ecb4d-0ca9-445d-8beb-262ca378e91a',"id",'invoices:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a1237c3e-8d13-4245-8400-00f397441208',"id",'maintenance:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'bc722e16-3b6e-409a-b36c-a48a5789258b',"id",'messages:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e0a7418e-7523-425d-91b6-851063cf80d1',"id",'documents:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='customer-service' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('721367b6-8e38-487d-84c3-7f7ab2c11bdd',NULL,'Fastighetsskötare','facility-worker',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '894c511f-2188-4723-bb4e-6575d143d566',"id",'maintenance:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='facility-worker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '84869798-0414-413f-9c65-f1b88ba7ae72',"id",'maintenance:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='facility-worker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'eae65ed5-31ac-46b5-80c5-ada978962b7e',"id",'workorders:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='facility-worker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'a8f2195c-e3ef-4339-a60f-29c6aea7e35b',"id",'workorders:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='facility-worker' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c118fd2b-9f18-48ef-a8e1-31b075c098f2',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='facility-worker' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('7dde9886-5be1-4f4c-8dd2-78b1d0364036',NULL,'Besiktningsman','inspector',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '3db8c998-6adb-42a2-a7ae-47587698a3c7',"id",'inspections:*' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='inspector' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'e5a17e4d-89ce-4692-882f-3503a118798d',"id",'units:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='inspector' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '934d193a-b89f-425f-ae2e-3418d1d1dbf3',"id",'contracts:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='inspector' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '34219e39-f857-4ff8-85df-fd70dce2a523',"id",'documents:create' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='inspector' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '0f4cb261-4bc6-432a-9ba6-5328597d5fd0',"id",'documents:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='inspector' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('2cc435d7-8217-4f93-87d2-075d2258bf5d',NULL,'Entreprenör','contractor',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '95dab739-b593-46d3-b5f2-2286746d895f',"id",'workorders:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='contractor' ON CONFLICT ("roleId","permission") DO NOTHING;
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT '0fba2641-6ae5-4954-adcf-bbdc1ec77982',"id",'workorders:update' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='contractor' ON CONFLICT ("roleId","permission") DO NOTHING;

INSERT INTO "Role" ("id","organizationId","name","slug","isSystem","updatedAt") VALUES ('7346e0b4-74b0-49e2-8a98-964751e7c9e5',NULL,'Rapportläsare','report-viewer',true,now()) ON CONFLICT ("slug") WHERE "organizationId" IS NULL DO UPDATE SET "name"=EXCLUDED."name","isSystem"=true,"updatedAt"=now();
INSERT INTO "RolePermission" ("id","roleId","permission") SELECT 'c76fb88b-e7c3-40b8-8ad8-b9b918854c44',"id",'reports:read' FROM "Role" WHERE "organizationId" IS NULL AND "slug"='report-viewer' ON CONFLICT ("roleId","permission") DO NOTHING;

