-- Östgöta El Teknik Fastighetsplattform
-- Step: Extensions and enum types
-- Safe to run in filename order. This file is transactional.

BEGIN;
SET LOCAL search_path = public, extensions;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- CreateEnum
CREATE TYPE public."MasterDataDomain" AS ENUM ('CUSTOMERS', 'INVOICES', 'PAYMENTS', 'CREDIT_NOTES', 'REMINDERS', 'LEDGER', 'CONTRACTS');

-- CreateEnum
CREATE TYPE public."PersonRoleType" AS ENUM ('APPLICANT', 'TENANT', 'CO_APPLICANT', 'GUARANTOR', 'BUYER', 'CONTACT', 'HOUSEHOLD_MEMBER');

-- CreateEnum
CREATE TYPE public."PropertyStatus" AS ENUM ('ACTIVE', 'UNDER_RENOVATION', 'SOLD', 'ARCHIVED');

-- CreateEnum
CREATE TYPE public."UnitType" AS ENUM ('APARTMENT', 'APARTMENT_SALE', 'COMMERCIAL', 'OFFICE', 'RETAIL', 'WAREHOUSE', 'GARAGE', 'PARKING', 'STORAGE', 'STUDENT', 'SHORT_TERM', 'LAND', 'PROPERTY_SALE');

-- CreateEnum
CREATE TYPE public."UnitStatus" AS ENUM ('DRAFT', 'NOT_PUBLISHED', 'UPCOMING', 'PUBLISHED', 'APPLICATION_OPEN', 'VIEWING', 'OFFER_SENT', 'RESERVED', 'CONTRACT_SENT', 'RENTED', 'FOR_SALE', 'BIDDING', 'SOLD', 'RENOVATING', 'BLOCKED', 'NOT_RENTABLE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE public."MediaKind" AS ENUM ('IMAGE', 'VIDEO', 'FLOORPLAN', 'DOCUMENT');

-- CreateEnum
CREATE TYPE public."ListingCategory" AS ENUM ('RENTAL', 'SALE', 'COMMERCIAL', 'PARKING');

-- CreateEnum
CREATE TYPE public."ListingStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'PAUSED', 'UNPUBLISHED', 'COMPLETED');

-- CreateEnum
CREATE TYPE public."ApplicationStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'RECEIVED', 'UNDER_REVIEW', 'NEEDS_SUPPLEMENT', 'QUALIFIED', 'NOT_QUALIFIED', 'VIEWING_OFFERED', 'VIEWING_BOOKED', 'OFFER_SENT', 'ACCEPTED', 'DECLINED', 'CONTRACT_SENT', 'CONTRACT_SIGNED', 'CLOSED', 'WITHDRAWN');

-- CreateEnum
CREATE TYPE public."ApplicationMemberRole" AS ENUM ('MAIN_APPLICANT', 'CO_APPLICANT', 'HOUSEHOLD_MEMBER', 'CHILD', 'GUARANTOR');

-- CreateEnum
CREATE TYPE public."ViewingKind" AS ENUM ('INDIVIDUAL', 'GROUP', 'DIGITAL', 'SELF_SERVICE');

-- CreateEnum
CREATE TYPE public."ViewingAttendeeStatus" AS ENUM ('INVITED', 'BOOKED', 'WAITLISTED', 'CHECKED_IN', 'ATTENDED', 'NO_SHOW', 'CANCELLED');

-- CreateEnum
CREATE TYPE public."OfferStatus" AS ENUM ('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN');

-- CreateEnum
CREATE TYPE public."ContractType" AS ENUM ('RESIDENTIAL', 'COMMERCIAL', 'PARKING', 'GARAGE', 'STORAGE', 'SHORT_TERM', 'SUBLEASE', 'ADDENDUM', 'GUARANTEE');

-- CreateEnum
CREATE TYPE public."ContractStatus" AS ENUM ('DRAFT', 'INTERNAL_REVIEW', 'APPROVED', 'SENT_FOR_SIGNING', 'PARTIALLY_SIGNED', 'SIGNED', 'ACTIVE', 'TERMINATED', 'ENDED', 'RESCINDED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE public."ContractPartyRole" AS ENUM ('LANDLORD', 'TENANT', 'CO_TENANT', 'GUARANTOR');

-- CreateEnum
CREATE TYPE public."TerminationStatus" AS ENUM ('REQUESTED', 'CONFIRMED', 'INSPECTION_BOOKED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE public."InspectionType" AS ENUM ('PRE_MOVE_OUT', 'FINAL', 'MOVE_IN');

-- CreateEnum
CREATE TYPE public."InvoiceStatus" AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'REMINDED', 'COLLECTION', 'CREDITED', 'CANCELLED', 'DISPUTED');

-- CreateEnum
CREATE TYPE public."SyncJobStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED');

-- CreateEnum
CREATE TYPE public."ReviewItemStatus" AS ENUM ('PENDING', 'RESOLVED', 'REJECTED');

-- CreateEnum
CREATE TYPE public."MaintenanceStatus" AS ENUM ('RECEIVED', 'CONFIRMED', 'ASSESSING', 'NEEDS_INFO', 'ASSIGNED', 'BOOKED', 'IN_PROGRESS', 'WAITING_TENANT', 'WAITING_CONTRACTOR', 'WAITING_MATERIAL', 'DONE', 'QUALITY_CHECK', 'CLOSED', 'REJECTED', 'REOPENED');

-- CreateEnum
CREATE TYPE public."MaintenancePriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

-- CreateEnum
CREATE TYPE public."WorkOrderStatus" AS ENUM ('CREATED', 'OFFERED', 'ACCEPTED', 'REJECTED', 'BOOKED', 'IN_PROGRESS', 'DONE', 'APPROVED', 'INVOICED', 'CANCELLED');

-- CreateEnum
CREATE TYPE public."DocumentType" AS ENUM ('CONTRACT', 'TERMINATION', 'INSPECTION_PROTOCOL', 'KEY_RECEIPT', 'INFO_LETTER', 'INVOICE', 'CREDIT_NOTE', 'PAYMENT_PLAN', 'POWER_OF_ATTORNEY', 'SUBLEASE', 'TRANSFER', 'GUARANTEE', 'SALE_DOCUMENT', 'ENERGY_DECLARATION', 'FLOORPLAN', 'OTHER');

-- CreateEnum
CREATE TYPE public."NotificationChannel" AS ENUM ('EMAIL', 'SMS', 'IN_APP', 'PUSH');

-- CreateEnum
CREATE TYPE public."WebhookDeliveryStatus" AS ENUM ('PENDING', 'DELIVERED', 'FAILED', 'DEAD_LETTER');

-- CreateEnum
CREATE TYPE public."ImportJobStatus" AS ENUM ('PREVIEW', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'ROLLED_BACK');

COMMIT;
